import './styles.css';
import './music-history.css';
document.body.classList.add('vite-loaded');
import './modules/bible.js';
import './modules/chat.js';
import './modules/count.js';
import './modules/music.js';
import './modules/music-history.js';
import './modules/nextdns.js';
import './modules/style.js';
